### ISSUE TITLE
[Feature Request] Typescript declaration file

### ISSUE THREAD

**Issue by bruceauyeung** [jwagner/smartcrop.js#101]
very  amazing and handy lib ! would you please provide Typescript declaration file for it ?
i have already searched in https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types but found nothing.

**Comment by jwagner** [comment]
I'd be happy to accept one in a PR if you feel like giving it a shot. :)

**Comment by jwagner** [comment]
Got added in #100
