### ISSUE TITLE
Make gulp/grunt tasks

### ISSUE THREAD

**Issue by ionutvmi** [jwagner/smartcrop.js#11]
It would be awesome if we could have this working as a gulp and/or grunt task.

That way we could have it as a step in the build process and send the optimized images to the browser.

For the width and height parameters I'm thinking we could have some configuration in a json file:

```
{
     "filename.jpg": [{"width": 100, "height": 100}, {"width": 150, "height": 150}]
     ...
}
```
and for the output we could have something like filename-smartcorp-100-100.jpg so it can be easaly referenced in the templates.

What do you think ? Any other ideas ?

**Comment by jwagner** [comment]
It would be easy to do, just take the code from https://github.com/jwagner/smartcrop-cli/blob/master/smartcrop-cli.js and wrap it in a grunt/gulp task. So if you want that feel free to do that.

Is this how I *personally* use smartcrop? No, I use it for preselecting crops which can then be changed by the user. Smartcrop makes a good guess. But sometimes it just gets it wrong and then you need a way to overwrite it's guess.
