### ISSUE TITLE
Smartcrop for Swift

### ISSUE THREAD

**Issue by petarserbo** [jwagner/smartcrop.js#114]
Does the Smatrctop library for Swift exist or something similar to it? I can not find something like this for Swift anywhere

**Comment by jwagner** [comment]
I'm not aware of any port to Swift either. It probably shouldn't be too hard to port it yourself though. While the code is written in a bit of a convoluted way the algorithm itself is fairly simple: https://github.com/jwagner/smartcrop.js/blob/main/smartcrop.js#L380 and could probably be ported in a few hours.

**Comment by petarserbo** [comment]
Thank you!
