### ISSUE TITLE
Add CDN Example

### ISSUE THREAD

**Issue by simanacci** [jwagner/smartcrop.js#117]
Consider adding an example for code that doesn't use Javascript package managers.

**Comment by jwagner** [comment]
I guess I'm a bit ignorant here but why would anyone realistically not use a package manager for a project where smartcrop.js would make sense?

**Comment by simanacci** [comment]
Well, in my case I'm using Rust/Actix-Web and I only need Javascript for AJAX and cropping one photo rendered on a single page.
