### ISSUE TITLE
Combine with focuspoint

### ISSUE THREAD

**Issue by billymoon** [jwagner/smartcrop.js#12]
Would be nice if this library, instead of cropping, would simply set the cetral point for use in https://github.com/jonom/jquery-focuspoint

**Comment by jwagner** [comment]
Hey @billymoon,

This library does not crop images or find focal points it just returns possible crops. So it is about areas not points.

I'm not really convinced that the focus point approach is a good idea but I didn't look at it in too much detail. If you want to try to combine smartcrop with jquery-focuspoint you could just feed the centroid of the best crop returned from smartcrop into focuspoint. Something like:
```javascript
let crop = cropResult.topCrop;
let focalPointX = (crop.x+crop.width/2)/image.width;
let focalPointY = (crop.y+crop.height/2)/image.height;
```

I don't think this belongs into smartcrop itself, so I'm closing this issue.
