### ISSUE TITLE
Connect.js / Express.js Middleware

### ISSUE THREAD

**Issue by inadarei** [jwagner/smartcrop.js#15]
Jonas,

this module is fantastic! I loved it so much that decided to integrate it with connect.js/express.js middleware: https://github.com/inadarei/connect-thumbs in case somebody wants to easily use it on the server-side, in a Node environment. Hope that's helpful.

Cheers!

Irakli

**Comment by jwagner** [comment]
Cool, I added it to the readme! :)

**Comment by inadarei** [comment]
Thanks.
