### ISSUE TITLE
Thank you for creating this library

### ISSUE THREAD

**Issue by sadiqmmm** [jwagner/smartcrop.js#17]
I have created a rails gem called smartcrop-rails, a wrapper of smartcrop.js for rails application.

Here are the links:
Github: https://github.com/sadiqmmm/smartcrop-rails
Rubygems: https://rubygems.org/gems/smartcrop-rails

Can you include in your readme / wiki / Docs / any.

**Comment by koenpunt** [comment]
A gem for a single js file without any actual rails integration seems like a lot of overhead..

**Comment by jwagner** [comment]
I agree with you @koenpunt I don't like this wrapping javascript libraries in gems either. But if there are people who like that, who am I to judge. ;)

Added it to the README, thanks!
