### ISSUE TITLE
1 image transition example

### ISSUE THREAD

**Issue by bchate** [jwagner/smartcrop.js#20]
Dear Jonas,

I am very impressed by your code, thanks a lot for that.
Unfortunately I have no knowledge on javascript and I am a newbie in webpage creation. Consequently, I am totally lost with your slideshow example.

Would it be possible to add a simple example (a single image with transition) on your repository?

Regards,
Bruno

**Comment by jwagner** [comment]
This is a library for finding crops, not for doing slide shows. The slide show is just a random example of what this library could be used for. Please use a library that is made for creating transitions/slide shows.
