### ISSUE TITLE
What format does image have to be in?

### ISSUE THREAD

**Issue by rightaway** [jwagner/smartcrop.js#22]
The example in the README doesn't show how the `image` variable gets created. And the documentation says

> image: anything ctx.drawImage() accepts, usually HTMLImageElement, HTMLCanvasElement or HTMLVideoElement

Can it be changed to accept a string which is a path to an image file (for NodeJS)?

**Comment by jwagner** [comment]
No, I won't handle image decoding in smartcrop. The next version (living in the canvas independence branch) will allow plugin in different image processing libraries so it can be used with *gm* for instance.
