### ISSUE TITLE
Callback should take error as its first argument

### ISSUE THREAD

**Issue by rightaway** [jwagner/smartcrop.js#23]
In the signature `SmartCrop.crop(image, options, callback)`, the callback's signature is `function(result)`. But how do errors get discovered and handled. Shouldn't the signature be in the usual JS style like `function(error, result)`?

Not only would that allow to handle errors but it would also allow smartcrop to be used with any of the promisify libraries (such as `pify`, `thenify`, etc) so that it can be used with Babel's ES7 async/await for a non-callback coding style.

**Comment by jwagner** [comment]
What you call 'the usual JS style' is just a node convention.

The next version will most likely use promises. I guess that would adresses your issue.
