### ISSUE TITLE
Cross origin

### ISSUE THREAD

**Issue by OmarZeidan** [jwagner/smartcrop.js#26]
# A great plugin tho, well done!

I just have a question please, does it work with cross origin images request ?

For example, lets say I load my images from Amazon service, would form any issue ?

**Comment by jwagner** [comment]
The images need cors clearance, if the appropriate headers are set (http://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html) then yes it will work otherwise it will fail because reading an image without cors clearance is a security violation. I hope that helps.

Cheers,
Jonas

**Comment by Xaplink** [comment]
So images requested using ../images/image.png will fail is that what this is stating, I have to use full url like  http://domain.com/images/image.png
