### ISSUE TITLE
Test suite images

### ISSUE THREAD

**Issue by Jonas-WMDE** [jwagner/smartcrop.js#29]
Just wanted to provide you with some images that are not so well working with your algorithm.

https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Giraffa_camelopardalis_angolensis.jpg/675px-Giraffa_camelopardalis_angolensis.jpg

https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Berlin_-_Siegess%C3%A4ule_Gro%C3%9Fer_Tiergarten_2012.jpg/600px-Berlin_-_Siegess%C3%A4ule_Gro%C3%9Fer_Tiergarten_2012.jpg

https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Cheetah_Feb09_02.jpg/900px-Cheetah_Feb09_02.jpg

https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Ursus_arctos_-_Norway.jpg/600px-Ursus_arctos_-_Norway.jpg

**Comment by jwagner** [comment]
Hey, other Jonas :)

Thanks for the examples. These cases are problematic for the smartcrop algorithm indeed.
Adding a bias to prefer the upper part of images in portrait might help with these and some others. But in the end a simple algorithm like smartcrop will always be limited.

I won't add them to the test suite as I want to keep the images in there random. But I'll keep them in mind for future hackery. Maybe I'll create a edge cases collection or something along those lines.

Thanks again.

Cheers,
Jonas
