### ISSUE TITLE
here is a good example of SmartCrop.js: www.wallpaperpcmobile.com

### ISSUE THREAD

**Issue by shinebay** [jwagner/smartcrop.js#31]
www.wallpaperpcmobile.com uses smartcrop.js to itelligently crop wallpaper, a very good demo site of smartcrop.js
orginal wallpaper:http://www.wallpaperpcmobile.com/wallpaper/bird-on-a-branch-163656
cropped to 480*800 resolution:
http://www.wallpaperpcmobile.com/wallpaper/bird-on-a-branch-163656/download-480x800

**Comment by doncullen** [comment]
As there's already a good demo page (https://29a.ch/sandbox/2014/smartcrop/examples/testsuite.html), in addition to this being not an actual issue report, would propose closing this issue.
