### ISSUE TITLE
Making it smarter

### ISSUE THREAD

**Issue by Charuru** [jwagner/smartcrop.js#33]
Whereto from here? Are there any efforts to make it smarter and get more accurate? It's already pretty good so far for 80% of the cases, but I would like it to reach a higher level of accuracy.

**Comment by jwagner** [comment]
Tweaking the coefficients based on machine learning and a big dataset (http://saliency.mit.edu/ for instance) would be one way ahead.

I also have plans to integrate it with face detection in the future (for usage on the server/with node).

Another thing worth trying is different windowing functions for scoring the image based on the salience/interestingness. I highly doubt the current rule of thirds functions is optimal. ;)

**Comment by shinebay** [comment]
@jwagner To integrate face detection in smartcrop.js, you can refer to this js lib:https://trackingjs.com/ ,maybe it can help you

**Comment by jwagner** [comment]
Hey @shinebay tracking.js looks pretty cool. My current plan is to make smartcrop.js expandable and then create a face detection plugin.

**Comment by ajbogh** [comment]
I'd also like to suggest intelligent zooming similar to the [effects that Cloudinary offers](http://cloudinary.com/blog/beyond_face_detection_smart_cropping_in_the_cloud_using_imagga_and_cloudinary).

**Comment by jwagner** [comment]
@ajbogh it can already do that by setting minScale.

**Comment by ajbogh** [comment]
@jwagner thanks! I'll check it out.

**Comment by jwagner** [comment]
I have integrated support for facedetection (via 'boosting areas in the image) into the [1.0 branch](https://github.com/jwagner/smartcrop.js/pull/40). The testbed currently includes trackingjs and jquery.facedetection for face detection. smartcrop-cli supports using opencv via node-opencv for facedetection. I plan to release soon all of these soon. :)

**Comment by jwagner** [comment]
I merged 1.0 so I close this issue.

**Comment by Charuru** [comment]
Is the demo up with this yet?

**Comment by jwagner** [comment]
Yes the demo has been updated: https://29a.ch/sandbox/2014/smartcrop/examples/testbed.html

**Comment by ajbogh** [comment]
You might want to change the image to a person. I found jquery.facedetection was pretty bad with animal faces. The best type of picture for this would be one where the person's face is not normally the area of interest when selecting a certain image dimension. With the jquery.facedetection it should ignore that area and highlight the face instead. I just think it would be nice to see the difference in a more complex image.

**Comment by jwagner** [comment]
@ajbogh I might change that image if I find something fitting with a permissive license. Most of my people photography is personal and constantly using [pictures of myself](https://29a.ch/2016/06/25/smartcrop-1) gets old too. :)

In a way I even find it good to start with an example that displays the weakness of these face detection libraries. It seems that they have been trained on mugshots rather than actual photographs of people. :)
