### ISSUE TITLE
Add configuration options to disable certain features

### ISSUE THREAD

**Issue by ajbogh** [jwagner/smartcrop.js#35]
Add configuration options (or document ways) to disable saturation and skin detection, among other features that take up time and may not be desirable.

I've noticed that smartcrop can be very time intensive in the client browser if there are many images that need to be processed. It can block the browser when the image gets very large. It would be nice to document ways to reduce the intelligence, and time taken in smartcrop in certain use cases.

The best approach is obviously to create a NodeJS image processor, but some websites don't have that luxury and we could help by not blocking the browser as much.

**Comment by jwagner** [comment]
Disabling one feature or another won't change much. 15% faster than slow is still slow. It would probably be possible to run a decent part of the algorithm in a worker but I'm not convinced that's worth the effort either. If possible I'd strongly suggest to run smartcrop as part of authoring a page ahead of time. As you stated it is too slow to run on multiple or large images on page load.

**Comment by jwagner** [comment]
No answer for over a week -> closing.
