### ISSUE TITLE
Mobile camera capture issue

### ISSUE THREAD

**Issue by sahanDissanayake** [jwagner/smartcrop.js#39]
Taking a photo on Samsun s6 portrait mode ( worldstar mode )
Upload it to smartcrop > testbed

The upload shows up sideways, For some reason.

<img width="753" alt="screen shot 2016-06-02 at 5 30 06 pm" src="https://cloud.githubusercontent.com/assets/5580680/15734851/b04e131e-28e7-11e6-8d20-a00b30e5ab18.png">

**Comment by jwagner** [comment]
Yes, because it doesn't take into account [exif orientation](http://jpegclub.org/exif_orientation.html). I have no plans of supporting this for the testbed.
