### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by trannamit95** [jwagner/smartcrop.js#41]
Hi !
This is first time I used smartcrop.js. Here is my code:
```
smartcrop = require('smartcrop'),
smartcrop.crop(dirPath + file_name, {width: 96, height: 96}).then(function(result){
   console.log('\nCrop:')
   console.log(result);
});
```
But when I run, It throw an error:
![image](https://cloud.githubusercontent.com/assets/15722352/16402394/74c167fe-3d16-11e6-8806-3ea570784f74.png)

**Comment by jwagner** [comment]
Nice to see you trying out smartcrop.

Quoting from the README:

> # Node
> 
> You can use smartcrop from nodejs via either [smartcrop-gm](https://github.com/jwagner/smartcrop-gm) (which is using image magick via gm) or [smartcrop-sharp](https://github.com/jwagner/smartcrop-sharp) (which is using libvips via sharp).
The [smartcrop-cli](https://github.com/jwagner/smartcrop-cli) can be used as an example of using smartcrop from node.

I guess I should add some clarification. Smartcrop.js is the base library, it only works in the browser out of the box. If you want to use it in node you will need to choose either smartcrop-gm or smartcrop-sharp.
You will also need to make sure that you can get the respective modules to work on your system (might or might not be hard on windows).

**Comment by trannamit95** [comment]
OH. Thank you @jwagner
