### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by persea-pro** [jwagner/smartcrop.js#43]
Thanks for this great job.
I am not a big fan of using * or commit reference into my bower.json.
Could you please create a release?

**Comment by jwagner** [comment]
I neglected to whole bower publishing thing a bit because I don't use it myself. I'll need to create or add a script for creating github releases. I'll do so when I find some time.

**Comment by jwagner** [comment]
It should be fixed now. I forgot to remove the deprecated version.js field in bower.json will do that in the next release. :)

**Comment by persea-pro** [comment]
I've tested the release this morning, that's work great.
Thank you for helping me to clean my bower.json file ;-)
