### ISSUE TITLE
smartcrop.js as Common.js Module

### ISSUE THREAD

**Issue by haroonabbasi** [jwagner/smartcrop.js#44]
Hi, is this library useable as common.js module,

as i tried to use it within appcelerator as common.js module but i got error "can't find document". 
As document is only available within browser how we can use this library as common.js module?

**Comment by jwagner** [comment]
Sort of. Common.js is just a module format, it does not come with any API for tasks such as image decoding. So you will need an adapter for the platform you are running on. I provide two adapters for node [smartcrop-sharp](https://github.com/jwagner/smartcrop-sharp) and [smartcrop-gm](https://github.com/jwagner/smartcrop-gm). You will need to develop an adapter like these for the appcelerator platform.
