### ISSUE TITLE
Is there any solution for .net framework?

### ISSUE THREAD

**Issue by elhampour** [jwagner/smartcrop.js#50]
Hi,

Thank you for your great component, but i need to do it in server side, and server side technology is asp.net MVC,  i wonder is there any solution for it ?

**Comment by jwagner** [comment]
I haven't done .net in many years so I can't tell you. The easiest solution is probably to just launch smartcrop-cli in a sub process but there might be fancier ways of integrating node.js and .net as well.

**Comment by Skleni** [comment]
A bit late to the party, but in case anyone else is looking for a .NET version: [here you go](https://github.com/softawaregmbh/smartcrop.net).
