### ISSUE TITLE
Support for images through standard input

### ISSUE THREAD

**Issue by Ravenstine** [jwagner/smartcrop.js#56]
Would be nice to be able to pipe an image into the CLI from something else.  My use case for that is where a user has uploaded an image through a web interface, and I want to get metadata and crop the photos before uploading them to S3.  I could use a tempfile, but it would be nicer to just use the file IO objects as is.

**Comment by jwagner** [comment]
smartcrop-cli already does this:
https://github.com/jwagner/smartcrop-cli/blob/master/smartcrop-cli.js#L139

```
jonas@fractal:~/Pictures/2017/04/13$ smartcrop - < 1290r_small.jpg 
{
  "topCrop": {
    "x": 504,
    "y": 0,
    "width": 1536,
    "height": 1536,
    "score": {
      "detail": 3275.496181869063,
      "saturation": 677.1039681853479,
      "skin": 442.4354769055732,
      "boost": 0,
      "total": 0.0007013169544048092
    }
  }
}
```
