### ISSUE TITLE
Error using smartcrop with FileReader()

### ISSUE THREAD

**Issue by rafaelxavierborges** [jwagner/smartcrop.js#58]
When I upload an image, I load this uploaded image to a <img>.
But I'm getting this error bellow:

Uncaught TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(CSSImageValue or HTMLImageElement or SVGImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap or OffscreenCanvas)'.

Bellow is my code:

$("#avatar").change(function(event) {
        var reader = new FileReader();
        $(reader).load(function (event) {
            image = $("#img-avatar");
    
            image.attr("src", event.target.result);
    
            smartcrop.crop(image, {width: 300, height: 300}).then(function(result){
                console.log(result);
            });
        });
        reader.readAsDataURL(event.target.files[0]);
    });

**Comment by jwagner** [comment]
Hello Rafael,

Please provide the information [CONTRIBUTING.md](https://github.com/jwagner/smartcrop.js/blob/master/CONTRIBUTING.md) asks for.
Namely at least:

- The browser & version used
- A URL to reproduce the error
- Other steps other necessary to reproduce the error

Randomly guessing what the snipped you posted might be doing is passing a jQuery object (image) to smartcrop. You must pass it a loaded image instead: 
```javascript
$(image).on('load', function() { smartcrop.crop(this, {width: 300, height: 300}).then(function(result){ console.log(result); });  } );
```
