### ISSUE TITLE
Inconsistency while cropping images

### ISSUE THREAD

**Issue by Samarkial** [jwagner/smartcrop.js#59]
I get different results while cropping the same image at differents

The original file : 
![2](https://user-images.githubusercontent.com/17046655/28638068-bb79417c-7211-11e7-9f87-5427157e2816.jpg)

Resulting files

25x25 : ![2_thumbnail_25x25](https://user-images.githubusercontent.com/17046655/28638050-af662152-7211-11e7-9692-64817e64bb1b.jpg)
32x32 : ![2_thumbnail_32x32](https://user-images.githubusercontent.com/17046655/28638053-af6bea74-7211-11e7-8151-d1f5317a19db.jpg)
35x35 : ![2_thumbnail_35x35](https://user-images.githubusercontent.com/17046655/28638051-af661220-7211-11e7-8e3f-dd04ce9b60d8.jpg)
40x40 : ![2_thumbnail_40x40](https://user-images.githubusercontent.com/17046655/28638052-af681a34-7211-11e7-8a5f-0343bf94c5e6.jpg)

I have other images with the same behavior, but not necessarely at the same size ( One crops bad at 24, but is fine at 23 and under as well as 25 and above).

This is from Nodejs (v.6.11.1) using the npm smartcrop-sharp (v.1.0.5)

**Comment by jwagner** [comment]
Hi Samarkial,

The inconsistency comes from the fact that smartcrop scales the image down do the expected output image size before evaluating the crops. This can lead to odd results with small images and long processing times for large images. I changed this behavior for 2.0 (beta):
https://github.com/jwagner/smartcrop.js/pull/60/files

As I didn't spend much time working on smartcrop in the past year this hasn't been released or tested yet. But if you feel like it you can give it a go of course. I would appreciate your feedback.

Cheers,
Jonas

**Comment by jwagner** [comment]
Should be fixed now.
