### ISSUE TITLE
Content Security Policy

### ISSUE THREAD

**Issue by Xaplink** [jwagner/smartcrop.js#62]
The crop fails when I add

meta http-equiv="Content-Security-Policy" content="default-src 'self'"

for security perposes regarding xss how can I be able to fix this???

I think the cause of this is because your code creates script or img tags somewhere but I dont know where, can you help me with that please

**Comment by doncullen** [comment]
This may be related to your issue: https://github.com/jwagner/smartcrop.js/issues/26

**Comment by jwagner** [comment]
Hello @Xaplink smartcrop only creates canvas elements. It doesn't create any images or script tags (as far as I know). Please provide a link with a minimal testcase that reproduces the issue.

**Comment by Xaplink** [comment]
I call my images using ../images/image.png is that what causes the failor ????

**Comment by jwagner** [comment]
Please provide a link with a minimal testcase that reproduces the issue.

**Comment by Xaplink** [comment]
I cannot provide that as my website is still underconstruction please put the meta tag on the head of your html page that has the smartcrop you will see that it will not work here is the meta tag    <meta http-equiv="Content-Security-Policy" content="default-src 'self'">
