### ISSUE TITLE
add support for page detection

### ISSUE THREAD

**Issue by bchr02** [jwagner/smartcrop.js#63]
It would be great if smartcrop could also auto crop pages that are stored within images.

**Comment by jwagner** [comment]
Hello bchr02,

What do you mean with page detection?

**Comment by bchr02** [comment]
The ability to detect a piece of paper contained within an image and crop out the non essential areas that surround the paper.

**Comment by jwagner** [comment]
That sounds like a very specific task that should be handled in another library. I don't think this should be part of smartcrop.js.

**Comment by bchr02** [comment]
That’s too bad. Thanks anyways.
