### ISSUE TITLE
React

### ISSUE THREAD

**Issue by cyrus-za** [jwagner/smartcrop.js#64]
Can somebody help me implement this in react?

**Comment by jwagner** [comment]
Smartcrop is library for finding crops of images. React is a library for building user interfaces.

I'm really not sure what you mean by "implementing" a library for finding crops for images "in" a library for building user interfaces.

What exactly are you trying to accomplish?

**Comment by cyrus-za** [comment]
I'm trying to let my users upload a image with react dropzone and then crop
it. The problem is react has a virtual dom so I can't get you the image
element (or not without hacking react), what I can get though is the actual
file data in base 64.

**Comment by jwagner** [comment]
You should be able to access an image element in your virtual dom via a [ref](https://reactjs.org/docs/refs-and-the-dom.html], without any nasty hacks.

**Comment by cyrus-za** [comment]
Yes I can access it, but it doesn't exist as it's a file that is uploaded.
So I'd need to now go and display it (without crop) for a few milliseconds
and then access it in ref and crop it, which results in a flashing effect.
If smart crop could read the base64 image instead of a element, I could
crop it before I display it

**Comment by jwagner** [comment]
Just set visibility to hidden (or display: none) until you have all the information you need to display it properly?
