### ISSUE TITLE
If I want to do image by image?

### ISSUE THREAD

**Issue by devcodep** [jwagner/smartcrop.js#68]
Good
If I want to do image by image?

For example:

     <?php do { ?>
       <div class="card bg-dark text-white"> <img class="card-img" src="ad@/fotoslugares/<?php echo $row_fotoslugares['img_name']; ?>">

         <div class="card-img-overlay">
           <h5 class="card-title">Photo</h5>
           <p class="card-text">Photo text</p>
           <p class="card-text">Last updated 3 mins ago</p>
         </div>
       </div>
       <?php } while ($row_fotoslugares = mysql_fetch_assoc($fotoslugares)); ?>

**Comment by jwagner** [comment]
I have absolutely no idea what you mean, nor what the php snippet you posted is supposed to tell me.
I can only help you if you ask clear questions.

I'm not up to date with the php output escaping rules either, but the echo you have in there looks a lot like it might be vulnerable to xss. Please be careful with that.
