### ISSUE TITLE
Disable Rotation on Some Images

### ISSUE THREAD

**Issue by JZL003** [jwagner/smartcrop.js#7]
Hi,

For some images smartcrop rotates the image to fit it within the size constraints. That sometimes works but, especially with people, this makes the image look worse. Is there a way to disable that?

**Comment by jwagner** [comment]
smartcrop does not rotate any images to fit any constraints. My guess is that you are running into issues with [exif orientation](http://keyj.emphy.de/exif-orientation-rant/). I'd recommend you to fix that before you apply smartcrop. [This is how I fixed exif orientation in my film emulator](https://github.com/jwagner/analog-film-emulator/blob/master/src/image-helpers.js#L55).

**Comment by jwagner** [comment]
As I didn't get any reply I assume that it was exif orientation and closethe issue.
