### ISSUE TITLE
Add OpenCV.js face detection example

### ISSUE THREAD

**Issue by jwagner** [jwagner/smartcrop.js#71]
OpenCV now comes with some form of JavaScript version. It probably should be added to the testbed.

**Comment by jwagner** [comment]
Decided to load opencv from unpkg due to it's size.

**Comment by nandosangenetto** [comment]
Is that working? 

Does it work on server/Node?

**Comment by jwagner** [comment]
@nandosangenetto 
Yes, this is working at least on the client. But I wouldn't recommend it right now. I'd recommend node-opencv for doing face detection in node at the moment.

I've written a bit about this in the README of the next release as well in case you are curious.
https://github.com/jwagner/smartcrop.js/blob/b90229ed0b45c9358d93cebb1e6d6a685150413b/README.md#face-detection
