### ISSUE TITLE
Any way to crop the image into a circle, instead of a square?

### ISSUE THREAD

**Issue by Bengejd** [jwagner/smartcrop.js#74]
I am looking to crop an image into a circle, hopefully using this library, or a combination of this (to detect a person's face), and then cropping that image into a circle (limitation of another library that doesn't allow css intervention on an image).

**Comment by jwagner** [comment]
Hi Jordan,

For optimal results the second answer applies. You could also just look for a square crop (diameter x diameter) using the existing library and then apply your circle effect, that will likely yield acceptable results too.

Cheers,
Jonas

**Comment by jwagner** [comment]
Closed for lack of a reply.
