### ISSUE TITLE
Solution to this image?

### ISSUE THREAD

**Issue by igorescobar** [jwagner/smartcrop.js#78]
Hey guys,

I have this image:
![trouble image](https://user-images.githubusercontent.com/24032/39456436-5bbce844-4cde-11e8-9467-6c549328a3a7.jpg)

And this is the area smartcrop is giving me to use:
![croppy-buggy](https://user-images.githubusercontent.com/24032/39456450-6ec4779a-4cde-11e8-86b0-0210500bf806.jpg)

This is the first image that I'm getting this kind of result... Is there something I can do to avoid these?

I know that if I use smartcrop + opencv I can boost the areas with faces and I can get this result:
![right-crop](https://user-images.githubusercontent.com/24032/39456504-b5a6b9b6-4cde-11e8-9d86-6634f38a72ba.jpg)

But I really don't want add opencv to my stack. It's too heavy I was hoping to get this fixed without using heavy artillery. 

Ideas?

**Comment by jwagner** [comment]
https://github.com/jwagner/smartcrop.js/issues/67 might help once implemented but given the way the algorithm works there are always going to be pathological cases.

**Comment by jwagner** [comment]
Closed for lack of a reply.

**Comment by igorescobar** [comment]
I'm sorry. Yes, the solution mentioned on #67 might help since profile pictures with people you usually don't get very good results. I can provide a few of them if you are interested. Just let me know.
