### ISSUE TITLE
The algorithm of skin detect

### ISSUE THREAD

**Issue by taotao419** [jwagner/smartcrop.js#79]
Hi there ,

Could you provide the link of article of the algorithm of skin detect? I search some documents but nothing are fit for  algotihm in your program.

Thanks

**Comment by taotao419** [comment]
function skinColor(options, r, g, b) {
        var mag = sqrt(r * r + g * g + b * b);
        var rd = r / mag - options.skinColor[0];
        var gd = g / mag - options.skinColor[1];
        var bd = b / mag - options.skinColor[2];
        var d = sqrt(rd * rd + gd * gd + bd * bd);
        return 1 - d;
  }

**Comment by jwagner** [comment]
It's just an algorithm I made up on the spot. I tried a more scientific approach here: https://github.com/jwagner/smartcrop.js/tree/human-skin-color-clustering. In the end the results were similar enough for me not the change what was there and working.
I hope that helps.
