### ISSUE TITLE
Is is possible to generate a percentage center point instead of absolute boundary?

### ISSUE THREAD

**Issue by lijunle** [jwagner/smartcrop.js#81]
Hi, @jwagner 

This is an awesome library, thank you for creating it!

I am considering to use the library in production environment, with responsiveness support. However, the absolute cropped boundary numbers are not very friendly to responsiveness. If the calculation result is a center point with percentage, we can use the following CSS styles to stick to that center point, then it will show good in PC view or mobile view.

```js
const style = {
  backgroundImage: `url("${imageURL}")`,
  backgroundPosition: `${centerPoint.x}% ${centerPoint.y}%`
}
```

Now, I am calculating the central point of the crop result as the center point. That is working but not really accurate.

More ideas?

**Comment by lijunle** [comment]
I found another workaround, set the width=height=50px (or small), minScale=0,5 (or small). It will generate a square cropped area, use the central point of this area as center point. The result is more making sense.

**Comment by jwagner** [comment]
just take x/width*100 to get %.
