### ISSUE TITLE
Aspect ratio instead of pixel amount

### ISSUE THREAD

**Issue by mrzool** [jwagner/smartcrop.js#85]
I have a bunch of 3:2 images that I'd like to crop at 16:9 while keeping as much of the original image as possible. I'd like to do this locally using [smartcrop-cli](https://github.com/jwagner/smartcrop-cli).

Would this be possible using smartcrop.js? It would be a dream that comes true.

EDIT: Every picture has different pixel size, but the same 3:2 aspect ratio. If that's not possible with smartcrop.js native functionality, maybe with a shell script as a wrapper? 🤔🤔

**Comment by jwagner** [comment]
It is, you can just pass in width: 300, height: 200, minScale: 1 and it should work the way you want to.

**Comment by jwagner** [comment]
It's in the README:
```
  --faceDetection  perform faceDetection using opencv
```

**Comment by mrzool** [comment]
Oh my...long day for me I guess. Thanks a lot.
