### ISSUE TITLE
Base64

### ISSUE THREAD

**Issue by AlanSaracho** [jwagner/smartcrop.js#89]
Hi! I try to use this library in React Native, but in react native i don't have HTMLImages for input.
Can i pass base64 image or something else?

Thanks!

**Comment by jwagner** [comment]
I'm not sure how exactly the image handling work with react native but I'm sure there is a way. Once you figured that out you can provide you image operations to smartcrop like this: https://github.com/jwagner/smartcrop-gm/blob/master/index.js

**Comment by bmovement** [comment]
@AlanSaracho Did you ever have any luck using this library in RN?

**Comment by jwagner** [comment]
@bmovement As mentioned above you'd most likely need to write image ops that would use something like https://www.npmjs.com/package/react-native-canvas.
