### ISSUE TITLE
Ft Request - Object-Position: var% var%;

### ISSUE THREAD

**Issue by billymitchell** [jwagner/smartcrop.js#99]
I'd love it if this could return object position percentages. When used in conjunction with object-fit: cover, you can have "fluid" images that fill their container without losing their focus point. Note you could also use this with background-position: var% var% for IE support. 

https://developer.mozilla.org/en-US/docs/Web/CSS/object-position

**Comment by jwagner** [comment]
Hi Billy,

I think that's something different from what smartcrop does. Smartcrop tries to find the 'best' rectangular area, whereas that you'd want is a single point of interest. Is that correct?

Cheers,
Jonas
